appName: mongo-workout
replicaCount: 1
mongoVersion: "4.2.6"
mongoDBUsers:
  username: "my-user"
  db: admin
  passwordRef: "my-user-password"
  roles:
    name: clusterAdmin
    db: admin
    adminAnyDb: userAdminAnyDatabase
  scramCredentialsSecretName: "my-scram"
storageCompressor: zlib
secretPassword: "myPassword"
